# Generated by Django 5.1.2 on 2024-10-31 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNIQUE_Id', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('image', models.ImageField(upload_to='Product_IMG/IMG/%Y%m%d')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('NEW', 'NEW'), ('OLD', 'OLD')], max_length=100)),
                ('information', models.TextField()),
                ('descriptions', models.TextField()),
                ('stock', models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=100)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=200)),
                ('created_date', models.CharField(default=django.utils.timezone.now, max_length=1000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_app.brand')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_app.categories')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_app.color')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store_app.filter_price')),
            ],
        ),
    ]
